version: "3"

services:
  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    networks:
      - calibre
    volumes:
      - ./calibre-web/data:/config
      - ./calibre-web/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped

  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3001"
      - "222:22"

  nginx:                                                                            
    depends_on:                                                                     
      - calibre                                                                        
      - gitea

    build: ./nginx/
        
    container_name: nginx                                                      
    restart: always                                                                 

    volumes:                                                                        
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf                                    
      - ./nginx/static/gitea/:/etc/nginx/static/gitea/
      - ./web/public:/etc/nginx/static/hugo/ 
    networks: 
      - calibre
      - gitea
    ports:                                     
      - "80:80"  
        
networks:
  calibre:
    external: false
  gitea:
    external: false