baseURL = "http://localhost/"
languageCode = "pt-br"
title = "Self Host Everything"
theme = "cactus"
copyright = "sudoga"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "dracula"
tabWidth = 4

[params]
colortheme = "dark"
showAllPostsArchive = false

description = "Let's self host everything we can!"
mainSection = "posts"
mainSectionTitle = "Posts"
showAllPostsOnHomePage = true

dateFormat = "2006-01-02"

show_updated = true
showReadTime = true

